site_name: NTT Group
site_url:  https://www.nttdemo.de
site_description: 'virtual demo room'
site_author: 'Holger Imbery'
docs_dir: docs/

repo_name: 'https://github.com/the-cognitiveservices-ninja/demo-environment'
repo_url: 'https://github.com/the-cognitiveservices-ninja/demo-environment'
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2023 Holger Imbery

nav:
    - home: index.md
    - Demos: 
      - scripts/index.md
      - Dynamics 365 Customer Service (webchat): scripts/d365_text_chat.md
      - Dynamics 365 Customer Service (phone): scripts/d365_voice.md
      - tendfor: scripts/tendfor.md
    - changelog: changelog.md
    
theme:
  name: 'material'
  custom_dir: docs/overrides
  logo: assets/ntt_logo.png
  palette:
    primary: blue
  
  features:
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    

markdown_extensions:
  - meta
  - tables
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg


plugins:
  - tags:
      tags_file: tags.md
  - with-pdf:
      cover_title: NTT Group - demo environment
      cover_subtitle: Holger Imbery
      output_path: pdf/script.pdf
  - search:
       lang: en
  - git-revision-date
  - mkdocs-video

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js


  
